name: jax_bnre
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.2=pyhc872135_1
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.3.1
      - aiofiles==25.1.0
      - alembic==1.17.1
      - antlr4-python3-runtime==4.9.3
      - chex==0.1.90
      - colorlog==6.10.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - etils==1.13.0
      - flax==0.10.7
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - h5py==3.15.1
      - humanize==4.14.0
      - hydra-core==1.3.2
      - importlib-resources==6.5.2
      - jax==0.6.2
      - jaxlib==0.6.2
      - kiwisolver==1.4.9
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - msgpack==1.1.2
      - multipledispatch==1.0.0
      - nest-asyncio==1.6.0
      - numpy==2.2.6
      - numpyro==0.19.0
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - optax==0.2.6
      - optuna==4.5.0
      - orbax-checkpoint==0.11.28
      - packaging==25.0
      - pillow==12.0.0
      - protobuf==6.33.0
      - psutil==7.1.3
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - rich==14.2.0
      - scipy==1.15.3
      - simplejson==3.20.2
      - six==1.17.0
      - sqlalchemy==2.0.44
      - tensorstore==0.1.78
      - tomli==2.3.0
      - toolz==1.1.0
      - tqdm==4.67.1
      - treescope==0.1.10
      - typing-extensions==4.15.0
      - zipp==3.23.0
prefix: /opt/anaconda3/envs/jax_bnre
